version: '3.7'

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    ports:
      - "10051:10051"
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - DB_SERVER_HOST=zabbix-db
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    networks:
      - zabbix-net
    depends_on:
      - zabbix-db
      - zabbix-web

  zabbix-db:
    image: postgres:14
    container_name: zabbix-db
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
    volumes:
      - zabbix_db_data:/var/lib/postgresql/data
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
    networks:
      - zabbix-net
    depends_on:
      - zabbix-db
      - zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=zabbix-agent
      - ZBX_SERVER_HOST=zabbix-server
    privileged: true
    pid: host
    networks:
      - zabbix-net
    depends_on:
      - zabbix-server

networks:
  zabbix-net:
    driver: bridge

volumes:
  zabbix_server_data:
  zabbix_db_data:
