version: '3.7'

services:
  postgres:
    image: postgres:15
    container_name: zabbix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      POSTGRES_DB: zabbix
    volumes:
      - zbx_pgsql:/var/lib/postgresql/data
    networks:
      - zbx_net

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:6.0-alpine
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGEURL: ""
      ZBX_STARTPOLLERS: 20
      ZBX_STARTSNMPTRAPPER: 5
      ZBX_STARTSNMPPOLLER: 20
      ZBX_CACHESIZE: 512M
      ZBX_STARTVMWARECOLLECTORS: 2
    ports:
      - "10051:10051"
    volumes:
      - zbx_server_conf:/etc/zabbix:z
    networks:
      - zbx_net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:6.0-alpine
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Seoul
    ports:
      - "8080:8080"
    volumes:
      - zbx_web_conf:/etc/zabbix/web:z
    networks:
      - zbx_net

networks:
  zbx_net:
    driver: bridge

volumes:
  zbx_pgsql:
  zbx_server_conf:
  zbx_web_conf:
